project:
  type: website

website:
  title: "michael decrescenzo"
  site-url: "https://mikedecr.netlify.app"
  repo-url: https://github.com/mikedecr/quarto-site
  repo-actions: [issue]
  favicon: submodules/imgs/img/favicon_telles.png
  navbar:
    right:
      - text: "About"
        file: about.qmd
      - text: "Blog"
        file: blog.qmd
      - icon: github
        href: https://github.com/mikedecr
      - icon: twitter
        href: https://twitter.com/mikedecr
  # social / sharing
  twitter-card:
    creator: "@mikedecr"
    card-style: summary_large_image
    image: submodules/imgs/img/ID_telles_1452x1452.png
  open-graph:
    image: submodules/imgs/img/ID_telles_1452x1452.png

format:
  html:
    theme: 
      light: [litera-tweaks.scss, fonts.scss]
      dark: [vapor, fonts.scss]
    # css: styles.css

