project:
  type: website

website:
  title: "michael decrescenzo"
  site-url: "https://mikedecr.netlify.app"
  # seen by RSS
  description: "political scientist turned high-frequency tradist"
  repo-url: https://github.com/mikedecr/quarto-site
  repo-actions: [issue]
  favicon: submodules/imgs/img/favicon_telles.png
  navbar:
    right:
      - text: "About"
        file: about.qmd
      - text: "Blog"
        file: blog.qmd
      - icon: github
        href: https://github.com/mikedecr
      # gets the listings content in blog.qmd (feed: true)
      - text: "RSS"
        href: blog.xml
      - text: "Bsky"
        href: https://bsky.app/profile/mikedecr.bsky.social
  # social / sharing
  twitter-card:
    image: "/submodules/imgs/img/ID_telles_1452x1452.png"
    # creator: "@mikedecr"
    # card-style: summary_large_image
  open-graph:
    image: submodules/imgs/img/ID_telles_1452x1452.png

format:
  html:
    theme: 
      light: [litera-tweaks.scss, fonts.scss]
      dark: [vapor, fonts.scss]
    # css: styles.css

